website/game_app/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', Index.as_view(), name='home'),
    path('profile/<slug:username>/', ProfileView.as_view(), name='profile'),
    path('signup', SignUpUser.as_view(), name='signup'),
    path('login', LoginUser.as_view(), name='login'),
    path('bd/', create),
    path('search/', search.as_view(), name='search'),
    path('logout/', LogOutUser, name="logout"),
    path('game/<slug:slug>/', GameView.as_view(), name='game'),
    path('<slug:slug>/', ReviewView.as_view(), name="post_review"),
    path('library/recommendation-list/', RecView.as_view(), name='rec'),
    path('support/send-question/', TechSupportView.as_view(), name='support'),
    path('support/subscribe/', SubscribeView.as_view(), name='subscribe'),
    path('chat/group/', ChatView.as_view(), name="chat"),

]

website/website/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from website import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('game_app.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/game_app/models.py
from django.core.mail import EmailMultiAlternatives
from django.db import models
from django.db.models.signals import post_save, pre_save, post_init
from django.dispatch import receiver
from django.template.loader import render_to_string
from django.utils import timezone
from django.contrib.auth.models import User
from django.conf import settings


class Genres(models.Model):
    name = models.CharField(max_length=30, db_index=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'жанр'
        verbose_name_plural = 'жанры'


class Platforms(models.Model):
    name = models.CharField(max_length=30, db_index=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'платформа'
        verbose_name_plural = 'платформы'


class Game(models.Model):
    game_id = models.IntegerField(primary_key=True, db_index=True)
    name = models.CharField(max_length=200)
    genres = models.ManyToManyField(Genres)
    platforms = models.ManyToManyField(Platforms)
    release_date = models.DateField(null=True)
    developer = models.CharField(max_length=50)
    description = models.TextField(blank=True)
    cover = models.CharField(null=True, max_length=200)
    slug = models.CharField(null=False, max_length=200)
    rating = models.PositiveSmallIntegerField(null=True)
    rating_count = models.PositiveIntegerField(null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'игра'
        verbose_name_plural = 'игры'


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True, db_index=True)
    avatar = models.ImageField(upload_to="photos/%Y/%m/%d/", null=True, blank=True)
    nickname = models.CharField(max_length=30, blank=False)

    def __str__(self):
        return self.nickname

    class Meta:
        verbose_name = 'профиль'
        verbose_name_plural = 'профили'


class Reviews(models.Model):
    text = models.TextField(blank=True)
    date = models.DateTimeField(auto_now=True)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"Отзыв на {self.game.name} пользователем {self.user.username}"

    class Meta:
        verbose_name = 'отзыв'
        verbose_name_plural = 'отзывы'


class Library(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    review = models.ForeignKey(Reviews, on_delete=models.CASCADE, null=True, blank=True)
    rate = models.PositiveSmallIntegerField(null=True, blank=True)
    added_at = models.DateField(null=False, auto_now_add=True)

    def __str__(self):
        return f"{self.user.username}: {self.game.name}"

    class Meta:
        verbose_name = 'библиотека'
        verbose_name_plural = 'библиотеки'


class ReviewSources(models.Model):
    name = models.CharField(max_length=20, db_index=True)
    link = models.URLField()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'источник'
        verbose_name_plural = 'источники'


class Websites(models.Model):
    game_id = models.IntegerField()
    name = models.CharField(max_length=30, null=False)
    url = models.CharField(max_length=200, null=False)

    class Meta:
        verbose_name = 'сайт'
        verbose_name_plural = 'сайты'

    def __str__(self):
        return str(self.game_id) + ' ' + self.name


class ReleaseDates(models.Model):
    game_id = models.IntegerField()
    platform = models.CharField(max_length=30, null=False)
    date = models.DateField(null=True)

    class Meta:
        verbose_name = 'Дата выхода'
        verbose_name_plural = 'Даты выхода'

    def __str__(self):
        return str(self.game_id) + ' ' + self.platform


class Images(models.Model):
    game_id = models.IntegerField()
    image_id = models.CharField(primary_key=True, null=False, max_length=200)

    class Meta:
        verbose_name = 'Картинки'
        verbose_name_plural = 'Картинки'

    def __str__(self):
        return self.image_id


class Videos(models.Model):
    game_id = models.IntegerField()
    video_id = models.CharField(primary_key=True, null=False, max_length=200)

    class Meta:
        verbose_name = 'Видео'
        verbose_name_plural = 'Видео'

    def __str__(self):
        return str(self.game_id) + ' ' + self.video_id


class TechSupport(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField(null=False, auto_now_add=True, editable=False)
    question = models.TextField(null=False, blank=False)
    answer = models.TextField(blank=True)
    IsAnswered = models.BooleanField(blank=True, default=False)

    class Meta:
        verbose_name = 'Техническая поддержка'
        verbose_name_plural = 'Технические поддержки'

    def __str__(self):
        return self.user.username


class MessageTopics(models.Model):
    name = models.CharField(max_length=250)
    users = models.ManyToManyField(User, blank=True, verbose_name='Подписчики')

    class Meta:
        verbose_name = 'Тема рассылки'
        verbose_name_plural = 'Темы для рассылок'

    def __str__(self):
        return self.name


class Message(models.Model):
    topic = models.ForeignKey(MessageTopics, on_delete=models.SET_DEFAULT, default='Topic was deleted')
    text = models.TextField()
    send_at = models.DateTimeField(auto_now=True)
    shown_to = models.ManyToManyField(User, blank=True, editable=False)
    isSend = models.BooleanField(blank=True, default=False)

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'

    def __str__(self):
        return self.topic.name


@receiver(post_save, sender=User)
def update_profile_signal(sender, instance, created, **kwargs):
    if created:
        profile = Profile.objects.create(user=instance)
        profile.nickname = instance.username
        instance.profile.save()


@receiver(post_save, sender=TechSupport)
def send_answer(sender, instance, created, **kwargs):
    if instance.IsAnswered:
        data = {
            'topic': f'Ответ на вопрос №{instance.pk}',
            'text': instance.answer,
            'user': 'Техническая поддержка сайта',
        }
        html_body = render_to_string('game_app/email_template.html', data)
        msg = EmailMultiAlternatives(data['topic'], html_body, from_email=settings.EMAIL_HOST_USER,
                                     to=[instance.user.email, ])
        msg.content_subtype = "html"
        msg.send()


@receiver(post_save, sender=MessageTopics)
def set_users_for_message(sender, instance, **kwargs):
    messages = Message.objects.filter(topic=instance)
    for message in messages:
        if not message.isSend:
            message.shown_to.set(instance.users.all())
            message.save()


@receiver(post_save, sender=Message)
def send_message(sender, instance, created, **kwargs):
    # instance.shown_to.set(instance.topic.users.all())
    # print( instance.shown_to.all())
    if instance.isSend:
        data = {
            'topic': instance.topic.name,
            'text': instance.text,
            'user': 'Техническая поддержка сайта',
        }
        emails = [user.email for user in instance.topic.users.all()]
        html_body = render_to_string('game_app/email_template.html', data)
        msg = EmailMultiAlternatives(data['topic'], html_body, from_email=settings.EMAIL_HOST_USER,
                                     to=emails)
        msg.content_subtype = "html"
        msg.send()


class ChatMessage(models.Model):
    question = models.ForeignKey("ChatMessage", on_delete=models.CASCADE, default=None, null=True, related_name='parent')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comment_author')
    content = models.TextField()
    date = models.DateTimeField(auto_now_add=True, editable=False)
    like = models.ManyToManyField(User, related_name='comment_like')
    dislike = models.ManyToManyField(User, related_name='comment_dislike')

    def get_prev_messages(self, timestamp, n=100):
        return ChatMessage.objects.filter(date__lte=timestamp)[:n]

    class Meta:
        verbose_name = 'Сообщениe чата'
        verbose_name_plural = 'Сообщения чата'

website/game_app/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from .models import *
from django import forms


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(max_length=20, label='Имя пользователя',
                               widget=forms.TextInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': ''}))
    password2 = forms.CharField(label='Повторите пароль', widget=forms.PasswordInput(attrs={'class': ''}))

    class Meta:
        model = User
        fields = {'username', 'password1', 'password2'}
        widgets = {
            'username': forms.TextInput(attrs={'class': ''}),
            'password1': forms.PasswordInput(attrs={'class': ''}),
            'password2': forms.PasswordInput(attrs={'class': ''}),
        }


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Имя пользователя', widget=forms.TextInput(attrs={'class': ''}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': ''}))


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Reviews
        fields = ('text',)


class LibraryForm(forms.ModelForm):
    class Meta:
        model = Library
        fields = ('rate',)


class ProfileForm(forms.ModelForm):
    avatar = forms.ImageField(required=False, label='Иконка пользователя:')
    nickname = forms.CharField(min_length=4, max_length=30, required=False, label='Имя пользователя:')

    avatar.widget.attrs.update({'class': 'avatar'})
    nickname.widget.attrs.update({'class': 'nickname'})

    class Meta:
        model = Profile
        fields = ('avatar', 'nickname')


class TechSupportForm(forms.ModelForm):
    class Meta:
        model = TechSupport
        fields = ('question',)

website/game_app/templates/game_app/TechSupport.html
{% extends 'game_app/base.html' %}
{% load static %}
{% block css %}
    <link type='text/css' rel="stylesheet" href="{% static 'game_app/css/support.css' %}" />
    <title>Обратная связь</title>
{% endblock %}
{% block main %}
<main>
    <div class="MessageForm">
        <form action="{% url 'subscribe' %}" method="post">
            {% csrf_token %}
            <label>Подписаться на рассылку:</label>
            <select name="topics" multiple size="4">
                {% for topic in topics %}
                    {% if topic in selected %}
                        <option selected>
                    {% else %}
                        <option>
                    {% endif %}
                    {{ topic }}</option>
                {% endfor %}
            </select>
            <button class="login">Подписаться</button>
        </form>
    </div>


  <form method="post">
      {% csrf_token %}
        <input class="topic-input" name="topic" type="text" placeholder="Тема вопроса" required/>
        <textarea name="text" type='text' placeholder="Опишите вопрос" required></textarea>
        <button class="login">Отправить</button>
  </form>
</main>
{% endblock %}

website/game_app/templates/game_app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <link rel="preconnect" href="https://fonts.googleapis.com"/>
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet"/>
    <link rel="shortcut icon" href="{% static 'game_app/icons/icons/cube.svg' %}" />
{% block css %}
{% endblock %}
</head>
<body>
    <div class="wrapper">
        <header>
            <div class="header-box">
                <a href="/"><img class="main-logo" src="{% static 'game_app/icons/icons/cube.svg' %}" style="filter: invert();"></a>
                <form action="{% url 'search' %}" class="search" method="get">
                    <label>
                        <input type="search" name="name" placeholder="Поиск">
                        <img src="{% static 'game_app/icons/icons/search.svg' %}" >
                    </label>
                </form>

                    {% if request.user.is_authenticated %}
                    <a href="{% url 'support' %}"><button class="login">Обратная связь</button></a>
                    <a href="/profile/{{ request.user.username }}"><button class="login">Личный кабинет</button></a>
                    {% else %}
                    <a href="{% url 'login' %}"><button class="login">Войти</button></a>
                    {% endif %}

            </div>
        </header>
{% block main %}
{% endblock %}
        <footer>
            <p>Здесь что-то есть, и возможно что-то будет</p>
        </footer>
    </div>
{% block js %}
{% endblock %}
</body>
</html>

website/game_app/templates/game_app/bd.html
{% extends 'game_app/base.html' %}
{% load static %}
{% block css %}
    <link type='text/css' rel="stylesheet" href="{% static 'game_app/css/index.css' %}" />
    <title>Главная страница</title>
{% endblock %}
{% block main %}
        <main
        </main>
{% endblock %}
{% block js %}
    <script src="{% static 'game_app/js/index.js' %}"></script>
{% endblock %}

website/game_app/templates/game_app/chat.html
{% extends 'game_app/base.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link type='text/css' rel="stylesheet" href="{% static 'game_app/css/chat.css' %}" />
    <title>Chat</title>
{% endblock %}
{% block main %}
        <main>
            <div class="container">
                    <div id="chat-log" >
                        {% for message in messages.all %}
                            {% if message.author.username == request.user.username %}
                                <div class="message sender" data-pk="{{ message.pk }}">
                            {% else %}
                                <div class="message receiver" data-pk="{{ message.pk }}">
                            {% endif %}

                                    <div class="user-name">
                                        <span>{{ message.author.username }}</span>
                                        <span>{{ message.date }}</span>
                                    </div>
                                     {% if message.question %}
                                    <div class="parent-message" data-pk="{{ message.question.pk }}">
                                        <div class="user-name">{{ message.question.author }}</div>
                                        <div class="message-content">{{ message.question.content }}</div>
                                    </div>
                                    {% endif %}
                                    <div class="message-content">{{ message.content | linebreaks }}</div>
                                    <div class="actions">
                                        <div class="like">
                                            {% if request.user in message.like.all %}
                                            <span class="material-symbols-outlined" data-fill="true">thumb_up</span>
                                            {% else %}
                                            <span class="material-symbols-outlined" data-fill="false">thumb_up</span>
                                            {% endif %}

                                            <span>{{ message.like.all|length }}</span>
                                        </div>
                                        <div class="like-users">
                                            {% for user in message.like.all %}
                                            {% if user.profile.avatar %}
                                            <img src="{{ user.profile.avatar.url }}" title="{{ user.profile.nickname }}">
                                            {% else %}
                                            <img src="{% static 'game_app/icons/icons/circle.svg' %}" title="{{ user.profile.nickname }}">
                                            {% endif %}
                                            {% endfor %}
                                        </div>
                                        <div class="dislike" >
                                            {% if request.user in message.dislike.all %}
                                            <span class="material-symbols-outlined" data-fill="true">thumb_down</span>
                                            {% else %}
                                            <span class="material-symbols-outlined" data-fill="false">thumb_down</span>
                                            {% endif %}
                                            <span>{{ message.dislike.all|length }}</span>
                                        </div>
                                        <div class="dislike-users">
                                              {% for user in message.dislike.all %}
                                                {% if user.profile.avatar %}
                                                    <img src="{{ user.profile.avatar.url }}" title="{{ user.profile.nickname }}">
                                                {% else %}
                                                    <img src="{% static 'game_app/icons/icons/circle.svg' %}" title="{{ user.profile.nickname }}">
                                                {% endif%}
                                            {% endfor %}
                                        </div>
                                        {% if request.user.is_authenticated %}
                                        <div class="reply">
                                            Ответить
                                        </div>
                                        {% endif %}
                                    </div>

                                </div>
                            {% empty %}
                                <div id="emptyText">
                                    Сообщений нет
                                </div>
                            {% endfor %}
                    </div>
                {% if request.user.is_authenticated %}
                <div class="send-container ">
                    <div class="parent-message none">
                        <div class="user-name"></div>
                        <div class="message-content"></div>
                        <div id="cancel"><span class="material-symbols-outlined">close</span></div>
                    </div>
                    <div class="form">
                        <div id="chat-message-input" contenteditable="true"></div>
                        <button id="chat-message-submit">Отправить</button>
                    </div>
                </div>
                {% endif %}
            </div>
        </main>
{% endblock %}
{% block js %}
    {{ room_name|json_script:"room-name" }}
    {{ request.user.username|json_script:"user_id" }}
    <script src="{% static 'game_app/js/chat.js' %}"></script>
{% endblock %}

website/game_app/templates/game_app/email_template.html
<p>Отправитель: {{ user }}</p>
<p>Тема вопроса: {{ topic }}</p>
<p>Описание вопроса:<hr>
{{ text|safe }}
</p>

website/game_app/templates/game_app/login.html
{% extends 'game_app/base.html' %}
{% load static %}

{% block css %}
    <link type='text/css' rel="stylesheet" href="{% static 'game_app/css/register.css' %}" />
    <title>Авторизация</title>
{% endblock %}

{% block main %}
<main>
    <div>
        <h1 style="display: block; text-align: center;">Авторизация</h1>
        <form method="post">
            {% csrf_token %}

            <div class="form-error">{{ form.non_field_errors }}</div>

            {% for f in form %}
                <label class ='form-label' for="{{ f.id_for_label }}">{{ f.label }}</label>
                {{f}}
                <div class="form-error"> {{ f.errors }} </div>
            {% endfor %}
            <button type="submit">Авторизоваться</button>
            <a href="{% url 'signup' %}">Нет аккаунта? Регистрация</a>
        </form>
    </div>

</main>
{% endblock %}

website/game_app/templates/game_app/profile.html
{% extends 'game_app/base.html' %}
{% load static %}
{% block css %}
    <link type='text/css' rel="stylesheet" href="{% static 'game_app/css/profile.css' %}"/>
    <title>Личный кабинет</title>
{% endblock %}
{% block main %}
        <aside>
            <div class="container">
                <div class="progress-bar"></div>
                <ul>
                    <li>Профиль</li>
                    <li>Сводка по библиотеке игр</li>
                    <li>Библиотека игр</li>
                    {% if request.user.username == object.username %}
                        {% if library %}
                        <li>Список рекомендаций</li>
                        {% endif %}
                    <li>Настройки</li>
                    <li>Выйти из аккаунта</li>
                    {% endif %}
                </ul>
            </div>
        </aside>
        <main>
            <section id="profile">
                {% if profile.avatar %}
                    <img src="{{ profile.avatar.url }}">
                {% endif %}
                <div class="profile-info">
                    <h1>{{ profile.nickname }}</h1>
                    <div class="date">Зарегистрирован: <span>{{ object.date_joined }}</span></div>
                    <div class="info">
                        <div>
                            <h4>Игр в библиотеке:</h4>
                            <h2>{{ game_count }}</h2>
                        </div>
                        <div>
                            <h4>Написано отзывов:</h4>
                            <h2>{{ review_count }}</h2>
                        </div>
                        <div>
                            <h4>Оценено игр:</h4>
                            <h2>{{ rate_count }}</h2>
                        </div>
                    </div>
                </div>
            </section>

            <section id="statistics">
                <div class="container">
                    <h2>Краткая сводка</h2>
                    <div>
                        <h2>Распределение платформ</h2>
                        <div class="plat-line">
                            {% if pc_count or ps_count or xbox_count or linux_count or android_count or ios_count or sega_count or nintendo_count %}
                            <div style='--per: 0.0;'></div>
                            {% else %}
                            <div style='--per: 1.0;'></div>
                            {% endif %}

                            {% if pc_count > 0 %}
                            <div style='--per: {{ pc_count|floatformat:"3u" }};' class="pc"></div>
                            {% endif %}

                            {% if ps_count > 0 %}
                            <div style='--per: {{ ps_count|floatformat:"3u" }};' class="ps"></div>
                            {% endif %}

                            {% if linux_count > 0 %}
                            <div style='--per: {{ linux_count|floatformat:"3u" }};' class="linux"></div>
                            {% endif %}

                            {% if ios_count > 0 %}
                            <div style='--per: {{ ios_count|floatformat:"3u" }};' class="ios"></div>
                            {% endif %}

                            {% if android_count > 0 %}
                            <div style='--per: {{ android_count|floatformat:"3u" }};' class="android"></div>
                            {% endif %}

                            {% if sega_count > 0 %}
                            <div style='--per: {{ sega_count|floatformat:"3u" }};' class="sega"></div>
                            {% endif %}

                            {% if xbox_count > 0 %}
                            <div style='--per: {{ xbox_count|floatformat:"3u" }};' class="xbox"></div>
                            {% endif %}

                            {% if nintendo_count > 0 %}
                            <div style='--per: {{ nintendo_count|floatformat:"3u" }};' class="nintendo"></div>
                            {% endif %}
                        </div>
                    </div>

                    <div>
                        <h2>Распределение оценок</h2>
                        <div class="col-diagram">
                            <canvas width="300" height="200" id="canvas"></canvas> 
                        </div>

                    </div>
                    
                </div>
            </section>

            <section id="library">
                <div class="container">
                    <h2>Библиотека игр</h2>
                    <ul>
                        {% for game in library %}
                            <li>
                                <a href="{% url 'game' game.game.slug %}">
                                <img src="https://images.igdb.com/igdb/image/upload/t_1080p/{{ game.game.cover }}.jpg">
                                </a>
                                <div>
                                    <p>{{ game.review.text }}</p>
                                    <p>Оценка: <span style='float: right'>{{ game.rate }}</span></p>
                                </div>

                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </section>

            {% if request.user.username == object.username %}

            {% if library %}
            <section id="recomendation-list">
                <div class="container">
                    <h2><a href="{% url 'rec' %}">Перейти к списку рекомендаций</a></h2>
                </div>
            </section>
            {% endif %}

            <section id="settings">
                <div class="container">
                    <h2>Настройки профиля</h2>
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <label>Аватар:</label><input type="file" name="avatar" accept="image/*" class="avatar" id="id_avatar">
                        <label>Имя пользователя:</label><input type="text" name="nickname" maxlength="30" minlength="4" class="nickname" id="id_nickname">
                        <button>Подтвердить</button>
                    </form>
                </div>
            </section>

            <section id="logout">
                <div class="container">
                    <a href="{% url 'logout' %}"><button>Выйти</button></a>
                </div>
            </section>
            {% endif %}
        </main>
{% endblock %}
{% block js %}
    <script>
        const data = {{ rates }}
    </script>
    <script src="{% static 'game_app/js/profile.js' %}"></script>
{% endblock %}

website/game_app/templates/game_app/recommendation.html
{% extends 'game_app/base.html' %}
{% load static %}
{% block css %}
    <link type='text/css' rel="stylesheet" href="{% static 'game_app/css/rec.css' %}" />
    <title>Список рекомендаций</title>
{% endblock %}
{% block main %}
        <main>
            <div class="container">
                <div class="text">
                    <p><span>РЕКОМЕНДОВАНЫЕ ИГРЫ</span>, СОСТАВЛЕННЫЕ ПО ВАШЕЙ ЛИЧНОЙ БИБЛИОТЕКЕ ИГР.</p>
                    <p>В РАСЧЁТЕ УЧАВСТВОВАЛИ <span>ПОЛЬЗОВАТЕЛИ</span>, С КОТОРЫМИ У ВАС СХОЖИ ИНТЕРЕСЫ.</p>
                    <p>ПРИ ЭТОМ УЧИТЫВАЛИСЬ <span>ОТЗЫВЫ</span> НА КАЖДУЮ ИГРУ.</p>
                    <p>НАДЕЕМСЯ, ЧТО ВЫ ДОВОЛЬНЫ РЕКОМЕНДАЦИЯМИ</p>
                </div>
                <div class="content-container">
                    {% if not games %}
                    <div class="error">К СОЖАЛЕНИЮ, ИЗ-ЗА МАЛОГО КОЛИЧЕСТВА СОВПАДЕНИЙ, МЫ НЕ СМОГЛИ ПОДОБРАТЬ ВАМ РЕКОМЕНДАЦИИ</div>
                    {% else %}
                    <div class="content-selector">
                        <input type="radio" id="game-selector" name="selector">
                        <input type="radio" id="user-selector" name="selector">
                        <label for="game-selector" class="selected">ИГРЫ</label>
                        <label for="user-selector">ПОЛЬЗОВАТЕЛИ</label>
                    </div>
                    <div class="content">
                        <div id="games">
                        <ul>
                            {% for game in games %}
                                <li>
                                    <a href="{% url 'game' game.slug %}">
                                    <img src="https://images.igdb.com/igdb/image/upload/t_1080p/{{ game.cover }}.jpg">
                                    </a>
                                </li>
                            {% endfor %}
                        </ul>
                        </div>
                        <div id="users" class="hidden">
                        <ul>
                            {% for user in users %}
                                <li>
                                    <a href="{% url 'profile' user.username %}">
                                        <img src="{{ user.profile.avatar.url }}">
                                        <h3>{{ user.username }}</h3>
                                    </a>
                                </li>
                            {% endfor %}
                        </ul>
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>


        </main>
{% endblock %}
{% block js %}
    <script src="{% static 'game_app/js/rec.js' %}"></script>
{% endblock %}